### ISSUE TITLE
 [BUG]

### ISSUE THREAD

**Issue by Raichan4** [amralsaleeh/HRMS#45]
![Screenshot (8718)](https://github.com/amralsaleeh/HRMS/assets/68491334/eab561e5-68fb-4890-83b7-588a2cd3d14f)
![Screenshot (8719)](https://github.com/amralsaleeh/HRMS/assets/68491334/b49ee04b-fd71-4826-aa44-37fb3d2eea59)
![Screenshot (8720)](https://github.com/amralsaleeh/HRMS/assets/68491334/38f88d04-3cec-4ee1-8886-c27cd18826f9)

Excuse me sir my name is Raichan, i admit it your project is wonderful but there is some bug in your project for details i attach some screenshots. Thank you.
![Uploading Screenshot (8718).png…]()

**Comment by amralsaleeh** [comment]
Hi @Raichan4,
that's because you don't have data in your database.

anyway, the seeders files have been added, so you can pull again and write the following command:
php artisan migrate:fresh --seed

and everything will run smoothly 🔥
