### ISSUE TITLE
You are not authorized! 🔐

### ISSUE THREAD

**Issue by budi77** [amralsaleeh/HRMS#71]
Successfully setup using the instructions but i got You are not authorized! 🔐 when i log in using the seed username. Pls help

**Comment by amralsaleeh** [comment]
Hi @budi77 

> Successfully setup using the instructions but i got You are not authorized! 🔐 when i log in using the seed username. Pls help

The issue is fixed now. You can clone the repo again and follow the instructions in the README file.
